### ISSUE TITLE
Grant access bar Greyed out

### ISSUE THREAD

**Issue by davidatpne** [ronakg/awesome-flickr-gallery-plugin#110]
Im trying to get the plugin to work on my site but I cant grant access. I have put the wp-admin call back in the correct place on flickr but all I get is the error "Awesome Flickr Gallery Error -" in the photo preview. Im keen to get this working because other plugins are not as good to be honest. my web site is www.scrappynw.com on wordpress 4.3.1 

thanks

**Comment by ronakg** [comment]
Your default settings page should look like this with appropriate values - https://camo.githubusercontent.com/990b6f44f3b060ba91821b7ce181097860614ca4/687474703a2f2f7777772e726f6e616b672e636f6d2f75706c6f6164732f73637265656e73686f742d342e6a706567

When you enter the Flickr API Secret, Grant Access button will be enabled.
