### ISSUE TITLE
Excessive blank divs created with plugin

### ISSUE THREAD

**Issue by jlascala** [ronakg/awesome-flickr-gallery-plugin#121]
The plugin is used on my site to display a handful of thumbnails in the footer.  It looks like it's working fine, but if you view the source code on the page the plugin is creating hundreds of empty divs.  Here's just a sample:

`<div class='afg-row'></div><div class='afg-row'></div><div class='afg-row'></div><div class='afg-row'></div><div class='afg-row'></div><div class='afg-row'></div><div class='afg-row'></div><div class='afg-row'></div><div class='afg-row'></div><div class='afg-row'></div><div class='afg-row'></div></div></div> 
`

What would be creating this?

**Comment by ronakg** [comment]
The blank divs have photos which are not displayed on the gallery but are part of the slideshow.

If they're not hindering you in any way, I'd like to close this issue.

**Comment by jlascala** [comment]
@ronakg  No, I wouldn't considered this closed.  Why would you close the issue without resolving it? 

How can that be fixed?  It's not like it repeats itself just once or twice. The code gets repeated hundreds of time.  I don't want the bloat on the page.
