### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by anshul1304** [ronakg/awesome-flickr-gallery-plugin#122]
Gallery pagination is not working for me.

When I right click on 2nd or 3rd pages and open in new tab, it's working. But if I click on 2nd or 3rd pages, it does not work.

I disabled all plugins and tried but the problem persists.

The site is here:
http://www.creativedezinesolutions.com/demo/seeincolors/dev/portfolio/

**Comment by PeterGrand** [comment]
Looks like yours is working now, but I'm still having this issue. Did you find a solution?

**Comment by anshul1304** [comment]
Am afraid not. I changed the plugin. It's a gallery section now and not the flickr plugin.

I did not get any plugin support :)

**Comment by PeterGrand** [comment]
It looks like it's actually a problem with Elegant Themes' code. We are both using their Divi theme and it appears to be putting in some javascript that overrides the behavior of these pagination links. I have submitted a ticket with them. Hopefully we'll see a fix in an upcoming version of Divi. I'll post here if I find a short term fix.

**Comment by anshul1304** [comment]
That makes sense. Thanks Peter!

**Comment by PeterGrand** [comment]
Support gave me a stopgap solution. Add this to Divi -> Theme Options -> Integration, "Add code to the < head > of your blog"

```
<script type="text/javascript">jQuery(document).ready(function(){
jQuery('.afg-page').on('click', function(){ window.location = jQuery(this).attr('href'); });
});</script>
```

**Comment by ronakg** [comment]
Is there anything pending on this issue? Sorry for such late response.
