### ISSUE TITLE
Sidebar widget for Flickr gallery

### ISSUE THREAD

**Issue by HkyMom4** [ronakg/awesome-flickr-gallery-plugin#125]
Hi there. I downloaded Awesome Flickr and was wondering how to create the sidebar widget that has the link to the gallery page. I'm a graphic designer, but new to code or anything of that nature. Thank you.

**Comment by ronakg** [comment]
You can just add a plain text sidebar widget and paste the gallery code there. Make sure to configure the gallery settings that are appropriate for a sidebar widget.
