### ISSUE TITLE
Not Seeing Photo Stream Preview

### ISSUE THREAD

**Issue by coleen4** [ronakg/awesome-flickr-gallery-plugin#126]
I have successfully connected two different personal websites (with two API Keys) to one personal Flickr account without any problems.

I have a work website and a work Flickr account that I'm trying to connect via AFG.  I've run out of ideas as to why I cannot successfully connect them. (I'm not seeing the Photostream Preview - it says "Awesome Flickr Gallery Error -"  I've followed all your instructions carefully and still no luck after several tries.  The only thing I can think of is that earlier today I deleted one of my two work Flickr accounts, however I used the still active account's URL to get the API key.  I would appreciate some advice. Thank you!

Thank you.

**Comment by ronakg** [comment]
What's the user id of the Flickr account you're trying to configure?

**Comment by coleen4** [comment]
We decided not to use the plug-in for our work website, so this is no
longer something I'm needing your help on.  But thank you for replying.

I think we had some issues with permissions on the work website's server,
which was different than my personal website servers (Go-Daddy), which
worked fine.

Thanks,
Coleen

**Comment by ronakg** [comment]
Thanks for getting back. I'll close this issue now.
