### ISSUE TITLE
Can it display videos from Flickr galleries?

### ISSUE THREAD

**Issue by Johnspick** [ronakg/awesome-flickr-gallery-plugin#146]
Hi there,

I've embedded a Flickr gallery in my website thanks to Awesome Flickr Gallery Plugin: http://www.hullharvestfeastival.org.uk/gallery/

The photos display very nicely but videos don't seem to appear. Should they?

Looking forward to any advice/ feedback.

Thanks in advance!

John

**Comment by ronakg** [comment]
Videos are not supported.
