### ISSUE TITLE
Photosets not showing

### ISSUE THREAD

**Issue by deanstreetdesigns** [ronakg/awesome-flickr-gallery-plugin#149]
After the upgrade to the latest version of Wordpress my galleries are not showing, all I see is Photoset not found

Any ideas?

**Comment by Clarejl** [comment]
I've got the same problem on a self hosted site which uses it lots.
Have just looked at another site that is instead on wordpress.com and their flickr gallery is fine. I guess it accesses flickr in a different way.
Let's hope it gets fixed soon

**Comment by pcreclame** [comment]
Same here. Must be related to the latest update on WP.

**Comment by msdup** [comment]
Same here. It seems to have happened after the WP 5.8.2 update.

**Comment by ronakg** [comment]
Can you guys also provide links to your gallery page?

**Comment by msdup** [comment]
[](https://www.local3ibew.org/electical-workers-minority-caucus-2014-photos/)

**Comment by msdup** [comment]
https://www.local3ibew.org/electical-workers-minority-caucus-2014-photos/[https://www.local3ibew.org/electical-workers-minority-caucus-2014-photos/](url)

**Comment by msdup** [comment]
https://www.local3ibew.org/electical-workers-minority-caucus-2014-photos/

**Comment by deanstreetdesigns** [comment]
http://www.deanstreetdesigns.com/photography-shane/

The last update I installed was for iThemes security, does anyone else use that plugin?

**Comment by ronakg** [comment]
Can you delete the cache from any of the caching plugins you might have?

I need more information to investigate this as I'm not seeing this problem on my own website or my local setup.

Are you trying to access private photosets or public photosets? What's your Flickr user-id? Give me one example of the photoset with the problem if possible.

**Comment by deanstreetdesigns** [comment]
I'm not using any caching plugins

this is the photoset that corresponds with the link above
https://www.flickr.com/photos/68386176@N05/albums/72157677341903022

**Comment by Clarejl** [comment]
Here's mine

**Comment by Clarejl** [comment]
Here's my broken site

http://sharpegraphics.co.uk/advertising/

**Comment by jdomke1** [comment]
Same issue for me... none of my flickr albums are showing. I've not done anything but my site was just automatically updated to WP 4.8.2
http://sq50.cawgcap.org/current-news/photo-gallery/

**Comment by ronakg** [comment]
Are you all able to see your photostream preview on the default settings page?

**Comment by mikecron** [comment]
Speaking for me, yes -- the Photostream preview shows just fine on the Default Settings page. Other modes of the plugin seem to work fine, it's just the Photoset/Album view that throws the error.

I've got a copy of the plugin enabled on a staging site on WP Engine and get this error in the log:

> [Thu Sep 21 21:27:33.200959 2017] [:error] [pid 32576] [client 108.20.172.172:44572] purge_varnish_cache() failed for: (localhost) #^(swimex\\.staging\\.wpengine\\.com)$# #(/photo-gallery(.*)|/wp-json/wp/v2/pages|^/$|/feed)#, referer: http://swimex.staging.wpengine.com/wp-admin/post.php?post=11189&action=edit

Not sure if that's helpful. Happy to offer any other data or access that might assist.

**Comment by pcreclame** [comment]
Here's one of mine. http://rondom.net/muziekfestival-fotos-2017/
That's one of 15 albums.
Emptied all the cache and even rebuild all the photosets.
I can see the photostream preview on the default settings page.

**Comment by Furanu** [comment]
The same problem I was just updated WP and since then the new galleries do not work. The previous galleries are still working well, the preview looks good... Will I have to wait for the plugin update?
This is a link to my last gallery working properly.
http://www.moviementarios.com/presentacion-de-blade-runner-2049/
Thanks.

**Comment by Clarejl** [comment]
I too can see the photostream preview

**Comment by sarahardwyn** [comment]
I have the same problem
http://www.sheilacraftpaintings.co.uk/original-oil-paintings/
http://www.sheilacraftpaintings.co.uk/prints/

**Comment by ronakg** [comment]
Can any of you give me access to your wordpress dashboard? I'll take a look at the issue this weekend.

Send me access details to me@ronakg.com.

**Comment by jdomke1** [comment]
I've downgraded back to the last WP version, 4.8.1, and the albums still aren't showing.

**Comment by jdomke1** [comment]
ronakg - Yes, I am able to see my photostream preview

**Comment by msdup** [comment]
I didn't try to investigate the issue further because I moved onto another plugin to get my photos on the site, but I wonder if creating a new API Key with Flickr might be helpful? I was also going to try downgrading to 4.8.1, but according to Jdomke1 it doesnt seem to work.

**Comment by jdomke1** [comment]
There's obviously something 4.8.2 did to screw up this plug. Following the directions for downgrading from http://dominiquej.com/how-to-downgrade-wordpress-to-previous-version/ it still didn't resolve the issue. That means whatever 4.8.2 did, it wasn't in the wp-admin or wp-includes folder or in the root. All that leaves is the wp-content which we can pretty much rule out and the database. Wishing I had a database backup from prior to the upgrade would let me know if I'm right. Hope this help ronalg tracking down what went wrong.

**Comment by jdomke1** [comment]
Now I found I had a backup of my site from 9/17. 2 days before the WP update... I restored and it still didn't fix the issue.

**Comment by jdomke1** [comment]
oh yeah, I did go onto Flickr and created a new API key but that didn't work either. The plug in clearly is authenticating because you see the preview of your photostream at the bottom of the plug in default settings screen

**Comment by jdomke1** [comment]
Seems to be specific to just using Gallery Source - Photoset. I switched over to Tags, set tags for all my photos in an album, and it now works. So, just get that Photoset feature working and everyone should be back to normal.

**Comment by ronakg** [comment]
Okay, here's an update.

Looks like something changed on Flickr's end, so now public access the photosets API is not working. If you've granted full access to AFG to your Flickr account, you won't face this issue as private access is working fine.

Wordpress update that came out recently has nothing to do with the issue, it's just a coincidence.

Workaround is to grant full access to AFG from the "Default Settings" page.

Steps for workaround:

1. Go to http://www.flickr.com/services/api/keys/
2. Copy the `Secret` and paste it into `Flickr API Secret` field on `Default Settings` page.
3. Click `Save Changes`
4. Click `Grant Access` button. This will open a new window that will ask you to give AFG permission to access your private photos on your Flickr account.

Once you follow these steps, all your galleries should start working. Let me know if you have any issues following the workaround.

I've raised this issue to Flickr, but not sure when they're going to fix it. They're usually really slow responding to such issues.

**Comment by msdup** [comment]
I tried that as well and it don't work to give AFG access. 

Using another plugin with the same exact API I am able to access specific albums/photosets.

**Comment by msdup** [comment]
I also noticed that when I clicked the GRANT ACCESS button it only took me to flickr.com, but not prompt for access permission to private photos appeared.

**Comment by ronakg** [comment]
Yes, didn't realize that Grant Access button is not working anymore. I'm fixing it right now.

Not sure how other plugin is still working because the issue is with Flickr's API. You can try it out on your own using Flickr's API explorer - https://www.flickr.com/services/api/explore/flickr.photosets.getInfo

- Put your photoset ID (the one from the photoset URL)
- Put your User ID (the one from Default Settings page)
- Click "Do not sign  call" to simulate public access.

You should see "Photoset not found" even for valid photosets/albums.

**Comment by msdup** [comment]
https://www.local3ibew.org/photonic_flickr_test/

This is the other plugin able to call my album/gallery. The short code needs the gallery/album number from the URL and it displays fine. AFG uses a drop down list of the albums associated with the account.
In any case you can see that it is work fine on the link above.

**Comment by ronakg** [comment]
I just pushed an updated version 3.5.6 with the fix for photosets not showing up.

I'll fix the "Grant Access" button going to flickr.com in a future update.

**Comment by Clarejl** [comment]
I can report that 3.5.6 worked for me. Just updated to it and everything was fine.

**Comment by pcreclame** [comment]
Update worked for me too!! Thanks Ronakg, awsome.

**Comment by RStehn** [comment]
Thank you, Ronakg, now it works!

**Comment by deanstreetdesigns** [comment]
Thanks, the plugin does now work correctly

**Comment by bocian74** [comment]
I'm struggling with the Grant Access button and can't authorize AFG. When I click it only takes me to flickr.com. Could you please look into it and fix? Thanks!

**Comment by Marebos** [comment]
Hi Ronak, your quote: "I just pushed an updated version 3.5.6 with the fix for photosets not showing up.
I'll fix the "Grant Access" button going to flickr.com in a future update."

But it's already april 2018. Any progress on the Grant Access button? It would be much appreciated, thanks!
