### ISSUE TITLE
Unable to set up AFG 3.5.0 properly. 

### ISSUE THREAD

**Issue by BleedingOrange** [ronakg/awesome-flickr-gallery-plugin#27]
I've installed AFG 3.5.0 but after filling in my Flickr user settings (ID and API Key) I can't click on the "Grant Access" button. Is this normal? 

And nothing shows up on my photostream preview but this message: 
"Awesome Flickr Gallery Error - error setting certificate verify locations: CAfile: /usr/local/share/curl/curl-ca-bundle.crt CApath: none" 
What does that mean? What do I have to do in order to make it work? 

Thanks in advance for your help!

**Comment by coleen4** [comment]
I have had success with connecting AFG to two websites and this 3rd one is giving me the Awesome Flickr Gallery Error -  (blank)

I've followed all of the above directions carefully, and also deleted my browsing history.
