### ISSUE TITLE
ColorBox not working; JS errors in the console

### ISSUE THREAD

**Issue by southernroutes** [ronakg/awesome-flickr-gallery-plugin#41]
Firstly, this is working perfectly on another website. However on the current site, the correct Filckr gallery loads, but the ColorBox effect does not. I noticed some JS errors in the colsole:

Uncaught TypeError: Cannot read property 'msie' of undefined  --  http://www.domain.com/wp-content/plugins/awesome-flickr-gallery-plugin/colorbox/jquery.colorbox-min.js?ver=3.9.2

Uncaught TypeError: undefined is not a function  --  http://www.domain.com/wp-content/plugins/awesome-flickr-gallery-plugin/colorbox/mycolorbox.js?ver=3.9.2

I tried disabling all other plugins to no avail. Any thoughts?

**Comment by marcocala** [comment]
Hi there Mr. Ronakg & Southernroutes,

this is Marco from Italy. I am working on a website for a friend of mine (eurovespa.it) nothing professional or so, with many pictures linked from Flickr. I discovered the plugin Awesome Flickr Gallery and it works perfectly on another website but on this I can't get the ColorBox doesn't work, pictures open in a new window with white background, one-by-one. Doing some research I got to this forum and read that Southernroutes managed to solve the problem but really I can't understand how. Could you please be so kind to explain? Thank you.
