### ISSUE TITLE
Updating from 3.5.1 to 3.5.3 breaks galleries

### ISSUE THREAD

**Issue by brightgirl** [ronakg/awesome-flickr-gallery-plugin#93]
My site is currently using AFG 3.5.1 and everything works. WP wants me to update to AFG 3.5.3 but when I do, it breaks all the galleries. The code shows on the page but no images :-(
Any advice?

**Comment by ronakg** [comment]
Can you paste the link to your gallery page here?

**Comment by brightgirl** [comment]
Here is one page that uses it: http://www.vfda.net/vfda-8th-annual-winter-conference/

There are many more that also use it under Events -> Event Photos

Presently I reverted to 3.5.1 so they are working. Let me know if you want me to update to 3.5.3 again so you can see them not working.

**Comment by ronakg** [comment]
I don't see anything alarming on your site. The 3.5.3 update should've worked. Can you try again, and this time clear all the caches from your wordpress installation. Specifically if you have any caching plugins installed. Try deleting browser cache too.

**Comment by brightgirl** [comment]
Hmmm… well I clear all the caches in the plugin and the browser both before and after updating to 3.5.3, but unfortunately it broke the galleries again.

I will leave it at 3.5.3 for awhile so you can see it broken: http://www.vfda.net/vfda-8th-annual-winter-conference/ and maybe that will help pinpoint the problem?

Karen

**Comment by ronakg** [comment]
Can you see if the plugin is getting deactivated when you update to 3.5.3? If so, please activate the plugin manually and it should work fine.

**Comment by brightgirl** [comment]
Bingo! That did the trick! Thank you so much!

I've never had a plugin deactivate on update before - such a simple thing, but I didn't even notice it!

Thanks again for all your help, really appreciated!

Karen

**Comment by ronakg** [comment]
Awesome!
