### ISSUE TITLE
Create gallery from date uploaded?

### ISSUE THREAD

**Issue by tsukinoblossom** [ronakg/awesome-flickr-gallery-plugin#98]
I have just installed Awesome Flickr Gallery and it is incredible! I was just wondering, is there a way to use the upload date as a gallery criteria? If not, could this be considered for a future update? In the interim I can use the date as a tag, but it is a bit tedious.

**Comment by ronakg** [comment]
You can sort photos by uploaded date. Check the "Sort order of photos" setting for different sorting options.

**Comment by tsukinoblossom** [comment]
I'm sorry, I guess I was unclear. I don't want to *sort* them by date, I want to create galleries that *only* post photos from a certain date. I'll figure something out though. Thank you again.
